// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Utilisation des variables d'environnement
// Assurez-vous que NEXT_PUBLIC_SUPABASE_URL et NEXT_PUBLIC_SUPABASE_ANON_KEY sont définies
// dans votre fichier .env.local (ou équivalent dans votre environnement de déploiement)
const SUPABASE_URL = import.meta.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// Vérification simple au cas où les variables ne seraient pas définies (utile pour le débogage)
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("Erreur: Les variables d'environnement Supabase ne sont pas définies !");
  console.error("Assurez-vous que NEXT_PUBLIC_SUPABASE_URL et NEXT_PUBLIC_SUPABASE_ANON_KEY sont configurées.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
